config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :notes
  get 'tags/:tag', to: 'home#index', as: :tag
  resources :questions
  resources :subtrends
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :answers
  resources :questions
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get 'home/index'
  get '/sear',to: 'questions#index'
  devise_for :users, :controllers => { sessions: "sessions", registrations: "registrations",:omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#indexmain"
  resources :users,only: [:show,:edit,:update]
  get '/users_list'=>'home#users_list'
  get '/tags_list'=>'home#tags_list'

  resources :questions do
    post 'like',   to: 'socializations#like'
    post 'follow', to: 'socializations#followQuestion'
  end

  resources :answers do
    post 'like',   to: 'socializations#likeAnswer'
  end
  resources :trends do
    post 'follow', to: 'socializations#followTrend'
  end
  resources :users do
    post 'follow', to: 'socializations#followUser'
  
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers ,foreign_key: :question_id,dependent: :destroy
  has_many :likes
  has_many :follows
  has_many :users,through: :answers
  validates :title ,presence: true,length:{maximum:240}

  acts_as_followable
  acts_as_likeable
  # attr_accessible :title
  has_many :taggings
  has_many :tags, through: :taggings

  acts_as_taggable_on :tags
  # acts_as_taggable
  def answerfeed question_id
    Answer.where(question_id: question_id).order(created_at: :desc)
  end

  def self.search(search)
    if search
      where('title ILIKE ?', "%#{search}%")
    else
      all
    end
  end
  def liked_by user_id, question_id
    Like.where(likeable_type: "Question",liker_id: user_id,likeable_id: question_id).length > 0
  end

  def like_string user_id,question_id
    if (liked_by user_id,question_id)
      return true
    else
      return false
    end
  end

  def followed_by user_id, question_id
    Follow.where(followable_type: "Question",follower_id: user_id,followable_id: question_id).length > 0
  end

  def follow_string user_id,question_id
    if (followed_by user_id,question_id)
      return true
    else
      return false
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:show, :edit, :update, :destroy]


  def index
    # @question=Question.search(params[:search])
    # byebug
  end
  # GET /questions/1  # GET /questions/1.json

  # GET /questions/new
  def show
    respond_to do |format|
      format.html{
        @question=Question.find(params[:id])
        @questagfeed = []
        @question.tag_list.each do |tag| 
          @questagfeed += Question.tagged_with(tag) 
        end
    
        @answer = Answer.new(question_id: params[@question.id])
        @answerfeed=@question.answerfeed @question.id
        # @comment = Comment.new(answer_id: params[@answer.id])
        # @commentfeed=@answer.commentfeed @answer.id
        

      }
      format.js{  }
    end







  end
  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id
    list_of_tags=question_params["tag_list"].split(",")
    list_of_tags.each do |tag|
      if Question.tagged_with(tag).length ==0
        var=Trend.new
        var.name=tag
        var.save!
      end
    end
    respond_to do |format|
      if @question.save
        Resque.enqueue(QuestionMailer,@question.id,current_user.id)

        format.html { redirect_to '/', notice: 'Question was successfully created.' }
        format.js{  }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render 'home/index' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    Like.all.where(likeable_type: "Question", likeable_id: @question.id)
    @question.destroy
    respond_to do |format|
      format.html { redirect_to '/', notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:title, :content, :user_id, :tag_list)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.erb
<head>
  <!--Import Google Icon Font-->
  <!-- <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> -->
  <!-- <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'> -->
  <!--Import materialize.css-->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css"> -->

  <!--Let browser know website is optimized for mobile-->
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"/> -->

  <style type="text/css">

    /* Imports */
    @import url(https://fonts.googleapis.com/css?family=Lato:400,300);



    .card{
      transition-duration: 0.3s;
      transition-property: box-shadow;
      -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
      transform: translateZ(3);
      /*box-shadow: 0 0 1px rgba(0, 0, 0, 0);*/
    }

    div.card:hover {

      box-shadow: 0 12px 12px rgba(0, 0, .6, .6);


    }
    .card-title{
      /*min-height: 11rem;*/
      /*line-height: 1.5rem;*/
      padding:1rem;
      border-bottom: 0px;
      font-size: 19px;
      font-weight: 300;
    }


    .card-title .fakeimage {
      width: 50px;
      height: 50px;
      /*margin: 0px 20px 0px 10px;*/
      float: left;
      border-radius: 100%;
      /*background: #aaa;*/
    }
    .card-title h2,  .card-title .wrap > p {
      margin-bottom: 10px;
      font-family: Lato, sans-serif;
      font-size: 1.2em;
      color: #222;
    }
    .card-title p {
      color: #696a6e;
      margin-right: 10px;
      margin-left: 10px;
      font-family: Lato, sans-serif;
      font-size: 0.9em;
      color: #aaa;
      float: left;
    }
    .card-title h5#head{
      color: #696a6e;
      font-weight: bold;
      font-size: 1.4rem;
      line-height: 110%;
      margin: 0 0 0 0;
      /*line-height: 3rem;*/
    }
    .card-title p#head{
      color: #696a6e;
      font-size: 0.8rem;
      font-weight: bold;
      margin-top: 0px;
      margin-bottom: 0px;
      /*line-height: 3rem;*/
    }
    .card-title p i {
      color: #696a6e;
      margin-right: 0;
      margin-left: 0;
      font-family: Lato, sans-serif;
      font-size: 0.7em;
      float: left;
      margin-top: 0px;
      margin-bottom: 0px;


    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-content.grey-text.text-darken-3{
      padding: 24px;
      padding-top: 0px;
      padding-bottom: 24px;
      border-radius: 0 0 2px 2px;
      padding-bottom: 2px;
      padding-top: 0px;
    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-title.row{
      margin-bottom:0px;
    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-title.row div.left.details{
      margin-left: 10px;

    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-content.grey-text.text-darken-3 div.row a i.material-icons.right{
      color:#949599;
    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div.row div.col.s12.m12.l12 div.answer div.userDetail div.card div.card-content.grey-text.text-darken-3 div.row a i.material-icons.right:hover{
      color:#0091ea;
    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div#answers div#modal1.modal.modal-fixed-footer.open div.modal-footer{
      height: 122px;
    }
.modal .modal-footer .btn-flat{
      background-color: #81d4fa;
    }
  </style>

</head>

<div class="answer">
  <div class="userDetail">
    <div class="card hoverable">
      <!--  answer.created_at.strftime("%B %d, %Y")-->
      <div class="card-title row" style="padding-bottom: 0px;">
        <div class="fakeimage left" style="margin-left: 10px;">

          <div class="picture"><%=avatar_for(current_user,size: 25)%></div>
        </div>
        <div class="left details">
          <h5 id="head"><%= answer.user.name %></h5>
          <p id="head" style="font-weight: 700"><%= time_ago_in_words(answer.created_at) unless answer.created_at.blank? %> ago</p>
          <br>
        </div>

      </div>
      <div class="card-content grey-text text-darken-3" style="padding-top: 0px; padding-bottom: 5px;">
        <p style="font-family: Lato"><%= raw answer.content %></p>
        <br>
        <div class="row" style="padding-bottom: 0px;">
          <%= link_to ('<i class="material-icons tooltipped right" data-position="bottom" data-delay="50" data-tooltip="Comment">forum</i>').html_safe, answer ,params[id: answer.id]%></button>

          <%if can? :update,answer%>
              <%= link_to ('<i class="material-icons tooltipped right" data-position="bottom" data-delay="50" data-tooltip="Edit Answer">create</i>').html_safe, answer %>

          <% end %>
          <%if can? :destroy,answer%>

              <%= link_to ('<i class="material-icons tooltipped right" data-position="bottom" data-delay="50" data-tooltip="Delete">delete</i>').html_safe, answer, method: :delete, data: {confirm: "Are you sure?"}%>

          <% end %>

          <a class="waves-effect waves-light grey btn tooltipped modal-trigger" data-position="bottom" data-delay="50" data-tooltip="Comment" href="#modal1">Comment</a>
          <% if answer.like_string(current_user.id,answer.id)== true%>
              <%= link_to ('<i class="material-icons right" >favorite</i>').html_safe, answer_like_path(answer), remote:true,method: :post ,id: "like_#{answer.id}" %>
          <%else%>
              <%= link_to ('<i class="material-icons right" >favorite_border</i>').html_safe, answer_like_path(answer), remote:true,method: :post ,id: "like_#{answer.id}" %>
          <%end%>


        </div>

      </div>
    </div>
  </div>


</div>
<!-- Modal Structure -->
<div id="modal1" class="modal modal-fixed-footer">
  <div class="modal-content">
    <div id="comments">
      <% @commentfeed.each do |comment| %>
          <%= render 'comment' , comment: comment %>
      <% end %>

    </div>

  </div>
  <div class="modal-footer">
    <div class="createComment">
      <%= form_for @comment, :url => comments_path(answer_id:answer.id), remote: true do |task|%>
          <%= task.label :comment %><br>
          <%= task.text_area :content %><br>
          <div class="actions">
            <%= task.submit id: 'create_comment_submit', class:"modal-action modal-close waves-effect waves-green btn-flat"%>
          </div>
      <% end %>
      <% if @comment.errors.any? %>
          <% @comment.errors.full_messages.each do |message| %>
              <%= message %>
          <% end %>
      <% end %>
    </div>

  </div>
</div>
<!-- <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script> -->
<!-- <script type="text/javascript">
$(document).ready(function(){
  $('.collapsible').collapsible({
      accordion : true
  });
});
</script> -->
<script type="text/javascript">
    $(document).ready(function(){
        // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
        $('#modal1').modal();
        $('#modal1').modal('open');
        $('.trigger-modal').modal();
        $('#modal1').modal('close');
        $('.tooltipped').tooltip({delay: 50});
    });
</script>

app/views/questions/_comment.html.erb
<style type="text/css">
  *{font-family:calibri;}

.avatar{
  border-radius:100px;
  width:80px;
  height:80px;
  float:left;
}
.message{
  position:relative;
  clear:both;
  width:100%;
}
.message .avatar{
  margin-top:5px;
}
.message p{
  float:left;
  font-family: calibri;
  color:#333;
  width:450px;
  margin:0;
  margin-left:20px;
  margin-top:5px;
  padding:10px;
  background-color:#fafafa;
  border:1px solid #eee;
  border-radius:5px;
  margin-bottom:10px;
  word-spacing:3px;
  line-height:22px;
}
.message p em.info{
  display:block;
  text-align:right;
  margin-top:10px;
  font-size:12px;
  font-weight:bold;
  color:#666;
}
.message p strong{
  display:block;
  color:#428bca;
  border-bottom:1px solid #ddd;
  margin-bottom:10px;
}
.message p strong em{
  font-weight :normal;
  color:#333;
  font-size:10pt;
}
.message .triangle{
  display:block;
  position:absolute;
  left:85px;
  top:25px;
  width: 0;
  height: 0;
  border-style: solid;
  border-width: 10px 15px 10px 0;
  border-color: transparent #eeeeee transparent transparent;
}

@media screen and (max-width: 1140px) {
  #global{width:100%;}
  .message{float:none;margin:auto;}
  .messages{float:none;margin:auto;}

}
@media screen and (max-width: 620px) {
  
  body{margin-right:60px;}
  .message .avatar,.inverse .avatar,.message .triangle,.inverse .triangle{display:none;}

}
</style>



  <div class="messages">
<div class="message">
  <div class="triangle"></div>
  <div class="avatar"><%=avatar_for(current_user,size: 20)%></div>
   
  <p><strong><%= comment.user.name %>,<em><%= time_ago_in_words(comment.created_at) unless comment.created_at.blank? %> ago</em></strong>
     <%= comment.content %>
     <br>
     
  <%if can? :update,comment%>
    <%= link_to 'Edit', comment %>
    <% end %>
    <%if can? :destroy,comment%>
    <%= link_to "Delete", comment, method: :delete, data: {confirm: "Are you sure?"}%>
    <% end %>

</p>
</div>
<br>



  </div>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <!-- <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/create.js.erb
$('#questions').prepend("<%= escape_javascript (render 'home/question', question: @question) %>");
$('#question_title').val("");
$('#question_content').val("");

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>asked at</th>
      <th>Content</th>
      <th>User</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.title,question %></td>
      <td><%= time_ago_in_words(question.created_at) %></td>
        <td><%= question.content %></td>

        <td><%= question.user.email %></td>
        <br>
        <td><%= link_to 'Show', question %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<head>
  <meta charset="UTF-8">
  <title>Answer</title>

  <!--Import Google Icon Font-->
  <!-- <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">-->
  <!-- <link rel='stylesheet prefetch' href='http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'> -->
  <!--Import materialize.css-->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">  -->

  <!--Let browser know website is optimized for mobile-->
  <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"/> -->



  <style type="text/css">

    /* Imports */
    @import url(https://fonts.googleapis.com/css?family=Lato:400,300);



    #cardques.card{
      margin-bottom: 10px;
      transition-duration: 0.3s;
      transition-property: box-shadow;
      -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
      transform: translateZ(3);

      /*box-shadow: 0 0 1px rgba(0, 0, 0, 0);*/
    }

    div#cardques.card:hover {

      box-shadow: 0 12px 12px rgba(0, 0, .6, .6);


    }
    #cardques .card-title{
      /*min-height: 11rem;*/
      /*line-height: 1.5rem;*/
      padding:1rem;
      border-bottom: 0px;
    }

    #cardques .card-title .fakeimage {
      width: 50px;
      height: 50px;
      /*margin: 0px 20px 0px 10px;*/
      float: left;
      border-radius: 100%;
      /* background: #aaa;*/
    }
    #cardques .card-title h2,  .card-title .wrap > p {
      margin-bottom: 10px;
      font-family: Lato, sans-serif;
      font-size: 1.2em;
      color: #222;
    }
    #cardques .card-title p {
      margin-right: 10px;
      margin-left: 10px;
      font-family: Lato, sans-serif;
      font-size: 0.9em;
      color: #aaa;
      float: left;
    }
    #cardques .card-title #quesuserdetail{
      margin-left: 65px;
      margin-top: 12px;

    }
    #cardques .card-title #quesuserdetail h4{
      font-family: 'Fresca', sans-serif;
      font-size: 1.5rem;
      line-height: 91%;
      margin: 0;
    }
    #cardques .card-title #quesuserdetail p{
      font-size: 16px;
      line-height: 91%;
      margin: 0;
    }
    div#quescontent{
      padding-top: 0px;
      padding-bottom: 2px;
    }
    div#quescontent h5{
      margin-top: 0;
      margin-bottom: 3px;
      color: #696a6e;
    }
    div#quescontent p{
      color: #6f6f6f;
    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div#cardques.card div#quescontent.card-content.grey-text div.row a i.material-icons.right{
      color:#949599;
    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div#cardques.card div#quescontent.card-content.grey-text div.row a i.material-icons.right:hover{
      color:#0091ea;
    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div.createAnswer form#new_answer.new_answer div.actions input#create_answer_submit.btn.right{
        color: #fff;
  background-color: #949599;
  border: none;
border-radius: 20px;
display: inline-block;
height: 40px;
line-height: 40px;
padding: 0 1rem;
text-transform: uppercase;
vertical-align: middle;
margin : 10px;
margin-top: 8px;
margin-bottom: 15px;
    }
    html body div#mithu.container div.row div.col.s12.m12.l7 div.createAnswer form#new_answer.new_answer div.actions input#create_answer_submit.btn.right:hover{
background: #00BCD4;
z-index: 8000;
    }
  </style>

</head>
<p id="notice"><%= notice %></p>

<div id="cardques" class="card hoverable">
  <!--  answer.created_at.strftime("%B %d, %Y")-->
  <div class="card-title">
    <div class="fakeimage">
      <div class="circle responsive-img valign profile-image"><%=avatar_for(current_user,size: 25)%></div>
    </div>
    <div id="quesuserdetail">

      <h4><%= @question.user.name %></h4>
      <p ><%= time_ago_in_words(@question.created_at) unless @question.created_at.blank? %> ago</p>

    </div>
  </div>
  <br>
  <div id="quescontent" class="card-content grey-text">

    <h5 style=" font-family: 'Cantarell, sans-serif';font-size: 22px;font-weight: bold;"><%= @question.title %></h5>
    <p style="font-family: 'Josefin Slab', serif; font-weight:bold;"><%= @question.content %></p>


    <div class="row">
      <%if can? :update,@question%>

          <%= link_to ('<i class="material-icons right">create</i>').html_safe, edit_question_path(@question)%>
      <% end %>
      <%if can? :destroy,@question%>

          <%= link_to ('<i class="material-icons right">delete</i>').html_safe, @question, method: :delete, data: {confirm: "Are you sure?"}%>

      <% end %>

    </div>
  </div>
</div>



<div class="createAnswer">
  <%= form_for @answer, :url => answers_path(question_id:@question.id), remote: true do |task|%>

      <% if @answer.errors.any? %>
          <% @answer.errors.full_messages.each do |message| %>
              <%= message %>
          <% end %>
      <% end %>

      <div class="field">
        <%= task.label :content %><br>
      </div>
      <div>
        <%= task.cktext_area :content, rows: 10 %>
      </div>
      <div class="actions">
        <%= task.submit id: 'create_answer_submit', class: 'btn right'%>
        

      </div>
  <% end %>




</div>



<div id="answers">
  <div class="row">


    <% @answerfeed.each do |answer| %>
        <div class="col s12 m12 l12">
          <%@comment = Comment.new(answer_id: params[answer.id])%>
          <% @commentfeed= answer.commentfeed answer.id %>
          <%= render 'answer' , answer: answer %>

        </div>
    <% end %>
  </div>

</div>

app/views/questions/show.js.erb
<% @answerfeed.each do |answer| %>
$('#answers').append("<%= escape_javascript (render 'questions/answer', answer: answer,question_id: @question.id) %>");
<% end %>