config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :notes
  get 'tags/:tag', to: 'home#index', as: :tag
  resources :questions
  resources :subtrends
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :answers
  resources :questions
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get 'home/index'
  get '/sear',to: 'questions#index'
  devise_for :users, :controllers => { sessions: "sessions", registrations: "registrations",:omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#indexmain"
  resources :users,only: [:show,:edit,:update]
  get '/users_list'=>'home#users_list'
  get '/tags_list'=>'home#tags_list'

  resources :questions do
    post 'like',   to: 'socializations#like'
    post 'follow', to: 'socializations#followQuestion'
  end

  resources :answers do
    post 'like',   to: 'socializations#likeAnswer'
  end
  resources :trends do
    post 'follow', to: 'socializations#followTrend'
  end
  resources :users do
    post 'follow', to: 'socializations#followUser'
  
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    respond_to do |format|
      format.html {
        @question = Question.new
        # byebug
        if params[:tag]
          @trend=Trend.where(name: params[:tag]).first
          # byebug
          @feed = Question.tagged_with(params[:tag]).paginate(:per_page => 20, :page => params[:page])
        elsif params[:search]
          @feed=Question.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
        else
          @feed=current_user.feed.paginate(:per_page => 7, :page => params[:page])
        end
      }
      format.js {}
    end
  end

  def indexmain
    respond_to do |format|
      format.html {
        @question = Question.new

        if params[:tag]
          @feed = Question.tagged_with(params[:tag]).paginate(:per_page => 4, :page => params[:page])
        else
          @feed=current_user.feed
          @latestfeed=current_user.latestfeed


          @tftags=Question.tag_counts_on(:tags).order('count desc').limit(5)
          @trendingfeed=[]

          @tftags.each do |tag|
            @trendingfeed += Question.tagged_with(tag)
          end
        end
      }
      format.js {}
    end
  end

  def users_list
   respond_to do |format|
    format.html {
      @users=User.all
    }
    format.js {}
  end
end

def tags_list

end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_question.html.erb
<head>
  <style type="text/css">


    div.card.ques {
      font-family: 'Roboto', sans-serif;
      display: block;
      width: 90%;
      height:auto;
      margin: 20px auto 40px;
      background-color: #ffffff;
      border-radius: 2px;
      overflow-y: hidden;
      overflow-wrap: normal;
      overflow-x: hidden;
      /*display: inline-block;*/
      transition-duration: 0.3s;
      transition-property: box-shadow;
      -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
      transform: translateZ(3);
      /*box-shadow: 0 0 1px rgba(0, 0, 0, 0);*/
    }

    div.card.ques:hover {

      box-shadow: 0 12px 12px rgba(0, 0, .6, .6);

    }
    div.card.ques div.card-title{
      padding: 16px;
    }

    div.card.ques div.card-title figure {
      width: 40px;
      height: 40px;
   /*   background-color: #dddddd;
      background-image: url(http://www.msudenver.edu/media/sampleassets/profile-placeholder.png);*/
     /* background-size: cover;*/
      margin: 0 16px 0 0;
      padding: 0;
      border-radius: 50%;
      float: left;
    }
    div.card.ques div.card-title div.text h1{
      font-size: 24px;
      font-weight: normal;
      line-height: 1;
      padding: 0;
      margin: 8px;
    }
    div.card.ques div.card-title div.text h2{
      color: #757575;
      font-size: 14px;
      font-weight: normal;
      line-height: 1;
      padding: 0;
      margin: 12px 0 0;
    }
    div.card.ques div.card-title div.text.small h1{
      margin-top: 1px;
      margin-left: 1px;
      font-size: 20px;
    }

    div.card.ques div.supporting_text {
      /*padding: 16px;*/
    }

    div.card.ques div.supporting_text h3{
      padding-left: 16px;
      font-size: 17px;
      margin-top: 0;
      margin-bottom: 0;
    }
    div.card.ques div.supporting_text p {
      font-size: 18px;
      line-height: 1.5;
      margin: 0;
      padding: 2px 5px 4px 13px;
    }
    div.card.ques div.row{
      padding: 1px;
      height: auto;
      margin-bottom: 0px;
    }

    div.card.ques div.card-action {
      position: relative;
      background-color: inherit;
      border-top: 1px solid rgba(160,160,160,0.2);
      padding: 4px 24px;
    }
    div.card.ques div.card-action div.right {
      float: right;
    }
    div.card.ques div.card-action a {
      color: #757575;
      /*height: 36px;*/
      margin: 0;
      margin-right: 0px;
      padding: 0px;
      background-color: #ffffff;
      border: none;
      font-size: 14px;
      text-transform: uppercase;
      border-radius: 2px;
    }

    div#questions div.row div.question div.userDetail div.card.ques div.supporting_text.text.small div.row div.card-action a i.material-icons{
      color:#949599;
      border-radius: 50%; 
    }
    div#questions div.row div.question div.userDetail div.card.ques div.supporting_text.text.small div.row div.card-action a i.material-icons:hover{
      color:#0091ea;
    }
    div#questions div.row div.question div.userDetail div.card.ques div.supporting_text.text.small div.row div.card-action a{
      color:#949599;
      border-radius: 50%; 
    }
    div#questions div.row div.question div.userDetail div.card.ques div.supporting_text.text.small div.row div.card-action a:hover{
      color:#0091ea;
    }
div.question div.userDetail div.card.ques.hoverable div.supporting_text.text.small div.row div.card-action a i.btn , 
 div#questions div.row div.question div.userDetail div.card.ques div.supporting_text.text.small div.row div.card-action a.btn{
  color: #fff;
  background-color: #949599;
  border: none;
border-radius: 20px;
display: inline-block;
height: 30px;
line-height: 30px;
padding: 0 1rem;
text-transform: uppercase;
vertical-align: middle;
}
div.question div.userDetail div.card.ques.hoverable div.supporting_text.text.small div.row div.card-action a i.btn:hover,
     div#questions div.row div.question div.userDetail div.card.ques div.supporting_text.text.small div.row div.card-action a.btn:hover{
      color: #fff;
      background-color:#00b8d4 ;
      z-index: 8000;
     
    }

    .card .card-action a:not(.btn):not(.btn-large):not(.btn-large):not(.btn-floating){
      margin-right: 0px;
    }
    [elevation='1'] {
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
    }

    [elevation='2'] {
      box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);
    }

    [elevation='3'] {
      box-shadow: 0 10px 20px rgba(0, 0, 0, 0.19), 0 6px 6px rgba(0, 0, 0, 0.23);
    }

    [elevation='4'] {
      box-shadow: 0 14px 28px rgba(0, 0, 0, 0.25), 0 10px 10px rgba(0, 0, 0, 0.22);
    }

    [elevation='5'] {
      box-shadow: 0 19px 38px rgba(0, 0, 0, 0.3), 0 15px 12px rgba(0, 0, 0, 0.22);
    }
  </style>
</head>
<div class="question">
  <div class="userDetail">
    <!-- <div class="col s12 m6 l6"> -->
    <div class="card ques hoverable" elevation="2">
      <div class="card-title">
        <figure elevation="1">
          <%=avatar_for(question.user,size: 20)%>
        </figure>
        <div class="text small">
          <h1 style="font-family: 'Fresca', sans-serif;"><%= question.user.name %></h1>
          <h2><%= time_ago_in_words(question.created_at) unless question.created_at.blank? %> ago</h2>
        </div>

      </div>
      <div class="supporting_text text small">
        <h3 style=" font-family: 'Cantarell, sans-serif';font-size: 22px;font-weight: bold;" class="truncate" ><%= link_to question.title ,question%></h3>

 <% if question.answers.first != nil %>
        <% ans = question.answers.first %>
        <p style="font-family: 'Josefin Slab', serif;" ><%= raw ans.content.truncate(500) %></p>

<% end %>
      
        <p style=" font-family: 'Capriola, sans-serif';font-size: 14px;">Tags:  <%= raw question.tag_list.map { |t| link_to t , tag_path(t) }.join(', ') %></p>




        <div class="row">
          <div class="card-action">
            <%= link_to ('<i class="btn">Answer</i>').html_safe, question ,params[id: question.id] %>
            <% if question.follow_string(current_user.id,question.id)== true%>
                <%= link_to(('<span class="">Unfollow</span>').html_safe, question_follow_path(question), remote:true,method: :post,id: "follow_#{question.id}",:class =>"waves-effect waves-light btn") %>
            <%else%>
                <%= link_to(('<span class="">follow</span>').html_safe, question_follow_path(question), remote:true,method: :post,id: "follow_#{question.id}",:class =>"waves-effect waves-light btn") %>
            <%end%>
            <div class="right">
              <% if question.like_string(current_user.id,question.id)== true%>
                  <%= link_to ('<i class="material-icons right">favorite_border</i>').html_safe, question_like_path(question), remote:true,method: :post ,id: "like_#{question.id}" %>
              <%else%>
                  <%= link_to ('<i class="material-icons right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Like">favorite_border</i>').html_safe, question_like_path(question), remote:true,method: :post ,id: "like_#{question.id}" %>
              <%end%>

              <%if can? :update,question%>
                  <%= link_to ('<i class="material-icons right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Edit">create</i>').html_safe, edit_question_path(question)%>
              <%end%>
              <%if can? :destroy,question%>
                  <%= link_to ('<i class="material-icons right tooltipped" data-position="bottom" data-delay="50" data-tooltip="Delete">delete</i>').html_safe, question, method: :delete, data: {confirm: "Are you sure?"}%>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- </div> -->
  </div>
</div>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/js/materialize.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.99.0/css/materialize.min.css" rel="stylesheet"/> -->
<script type="text/javascript">
  $('.tooltipped').tooltip({delay: 50});
</script>

app/views/home/_user_list.html.erb
<figure class="snip1515 hoverable">
  <div class="profile-image"><%=avatar_for(current_user,size: 70)%></div>
  <figcaption>
    <h3><%=user.name %></h3>
    <h4>Public Relations</h4>
    <p>The only skills I have the patience to learn are those that have no real application in life. </p>
    <div class="icons"><a href="#"><i class="ion-social-reddit"></i></a>
    

      <% if user.follow_string(current_user.id,user.id)== true%>
             <%= link_to('Unfollow', user_follow_path(user), remote:true,method: :post,class: "follow1_#{user.id}") %>
             <%else%>
             <%= link_to('follow', user_follow_path(user), remote:true,method: :post,class: "follow1_#{user.id}") %>
             <%end%>
      <a href="#"> <i class="ion-social-twitter"></i></a>
      <a href="#"> <i class="ion-social-vimeo"></i></a>
    </div>
  </figcaption>
</figure>

app/views/home/index.html.erb
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Home</title>
<style media="screen">
.apple_pagination {
background: #f1f1f1;
border: 1px solid #e5e5e5;
text-align: center;
padding: 1em;
cursor: default; }
.apple_pagination a, .apple_pagination span {
  padding: 0.2em 0.3em; }
.apple_pagination .disabled {
  color: #aaaaaa; }
.apple_pagination .current {
  font-style: normal;
  font-weight: bold;
  background-color: #bebebe;
  display: inline-block;
  width: 1.4em;
  height: 1.4em;
  line-height: 1.5;
  -moz-border-radius: 1em;
  -webkit-border-radius: 1em;
  border-radius: 1em;
  text-shadow: rgba(255, 255, 255, 0.8) 1px 1px 1px; }
.apple_pagination a {
  text-decoration: none;
  color: black; }
  .apple_pagination a:hover, .apple_pagination a:focus {
    text-decoration: underline; }
</style>
</head>
<body>
<!--   <a class="waves-effect waves-light cyan btn modal-trigger" href="#modal2">Ask Question !</a> -->
  <div id="modal2" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h4>ASK QUESTION</h4>
      <div class="createQuestion">
        <%= form_for @question, remote: true do |task|%>
        <div class="input-field">
          <%= task.text_field :title, class:'validate', id:'title' %>
          <%= task.label :title, for:'title' %><br>
        </div>
        <div class="input-field">
          <%= task.text_field :content, class:'validate materialize-textarea',id:'content'%><br>
          <%= task.label :content, for:'content' %><br>
          <!-- <textarea id="textarea1" class="materialize-textarea" data-length="120"></textarea> -->

        </div>
<div class="input-field">
  <%= task.label :tag_list, "Tags (separated by commas)" %><br />
  <%= task.text_field :tag_list %>
</div>
        <div class="modal-footer">
          <!-- <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">
          --> <div class="actions modal-action modal-close waves-effect waves-green cyan btn-flat">
              <%= task.submit id: 'create_question_submit' %>
            </div>

        </div>
        <% end %>
        <% if @question.errors.any? %>
        <% @question.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- <div class="col s12"> -->
  <!-- <div class="container"> -->
  <div id="questions">
    <a class="modal-trigger" href="#modal2">
      <div class=card class="z-depth-1" style="width: 93%;
          height: 72px;
          margin-bottom: 0;
          margin-top: 10px;
          margin-left: 25px;
          padding-left: 24px;
          padding-top: 0.5px;
          background: #ffffff;
          border: 2px solid #949599;">
        <a class="modal-trigger" href="#modal2" style="color: #949599; margin-bottom: 10px;"><h5>Ask your Question ?</h5></a>
      </div>
    </a>
    <div class="row">
      <% unless @trend.nil? %>
          <div class="chip" style="margin-top: 25px;margin-left: 50px;font-size: 30px;">
           <%=@trend.name%>
          </div>

          <% if @trend.follow_string(current_user.id,@trend.id)== true%>
              <%= link_to(('<span class="">Unfollow</span>').html_safe, trend_follow_path(@trend), remote:true,method: :post,id: "follow_#{@trend.id}",:class =>"waves-effect waves-light btn") %>
          <%else%>
              <%= link_to(('<span class="">follow</span>').html_safe, trend_follow_path(@trend), remote:true,method: :post,id: "follow_#{@trend.id}",:class =>"waves-effect waves-light btn") %>
          <%end%>

      <%end%>
      <% @feed.each do |question| %>
       <!-- <div class="col s12 m12 l12"> -->
      <%= render 'question' , question: question %>
   <!-- </div> -->
      <% end %>
    </div>
    <div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @feed %>
    </div>
    <%= will_paginate @feed, :container => false %>
  </div>

  </div>


  <!-- </div> -->
  <!-- <div class="container"> -->

  <!-- </div> -->
  <!-- </div> -->
  <script type="text/javascript">
  $(document).ready(function(){
    // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
    $('#modal2').modal({
      dismissible: true
    });
    $('#modal2').modal('open');
    $('.trigger-modal').modal();
    $('#modal2').modal('close');
    $('input#title, textarea#content').characterCounter();
  });
  </script>


</body>

app/views/home/index.js.erb
<% @feed.each do |question| %>
$('#questions').append("<%= escape_javascript (render 'home/question', question: question) %>");
<% end %>

app/views/home/indexmain.html.erb
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Home</title>
  <style media="screen">
    .card.trend, .card.latest{
      height: 360px;
      overflow-x: hidden;
      overflow-y: hidden;
      border: 1px solid #e2e2e2;

    }

  </style>
</head>
<body>
  <!--   <a class="waves-effect waves-light cyan btn modal-trigger" href="#modal2">Ask Question !</a> -->
  <a href="#trendingquestions" class="right btn btn-floating btn-large waves-effect waves-light indigo darken-2 pulse z-depth-4 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Trending"><i class="material-icons">trending_up</i></a>

  <!-- <div class="col s12"> -->
  <!-- <div class="container"> -->

  <div class="z-depth-0 transparent latest">
  <a href="#modal2" class="modal-trigger" data-target="modal2">
    <div class=card class="z-depth-1" style="width: 93%;
    height: 72px;
    margin-bottom: 0;
    margin-top: 10px;
    margin-left: 25px;
    padding-left: 24px;
    padding-top: 0.5px;
    background: #ffffff;
    border: 2px solid #949599;">
    <h5 style="color: #949599; margin-bottom: 10px;">Ask your Question ?</h5>
  </div>
</a>

<div id="modal2" class="modal modal-fixed-footer">
  <div class="createQuestion">
    <div class="modal-content">
      <h4>ASK QUESTION</h4>
      
      <%= form_for @question, remote: true do |task|%>
      <div class="input-field">
        <%= task.text_field :title, class:'validate', id:'title' %>
        <%= task.label :title, for:'title' %><br>
      </div>
      <div class="input-field">
        <%= task.text_field :content, class:'validate materialize-textarea',id:'content'%><br>
        <%= task.label :content, for:'content' %><br>
        <!-- <textarea id="textarea1" class="materialize-textarea" data-length="120"></textarea> -->

      </div>

      <div class="input-field">
        <%= task.label :tag_list, "Tags (separated by commas)" %>
        <%= task.text_field :tag_list %>
      </div>

    </div>
    <div class="modal-footer">
          <!-- <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">
        --> <div class="actions modal-action modal-close waves-effect waves-green cyan btn-flat">
        <%= task.submit id: 'create_question_submit' %>
      </div>

    </div>
    <% end %>
    <% if @question.errors.any? %>
    <% @question.errors.full_messages.each do |message| %>
    <%= message %>
    <% end %>
    <% end %>

  </div>
</div>




<div id="questions">
  <div class="row">

    <% @latestfeed.each do |question| %>
    <!-- <div class="col s12 m12 l12"> -->
    <%= render 'question' , question: question %>
    <!-- </div> -->
    <% end %>
  </div>

</div>


<!-- </div> -->
<!-- <div class="container"> -->
</div>
<div id="trendingquestions" class="z-depth-0 transparent trend">
  <div id="questions">
    <div class="row">
      <% @trendingfeed.each do |question| %>
      <!-- <div class="col s12 m12 l12"> -->
      <%= render 'question' , question: question %>
      <!-- </div> -->
      <% end %>
    </div>

  </div>
</div>

<!-- </div> -->
<!-- </div> -->
<script type="text/javascript">
  $(document).ready(function(){
    $('.modal').modal();
      $('#modal2').on('click', function() {
      });
    // the "href" attribute of the modal trigger must specify the modal ID that wants to be triggered
    $('#modal2').modal({
      dismissible: true
    });
    $('#modal2').modal('open');
    $('.trigger-modal').modal();
    $('#modal2').modal('close');
    $('input#title, textarea#content').characterCounter();
  });
</script>


</body>

app/views/home/indexmain.js.erb
<% @trendingfeed.each do |question| %>
$('#questions').append("<%= escape_javascript (render 'home/question', question: question) %>");
console.log("trending rendered");
<% end %>
<% @latestfeed.each do |question| %>
console.log("latest rendered");
$('#questions').append("<%= escape_javascript (render 'home/question', question: question) %>");
<% end %>

app/views/home/tags_list.html.erb
<style type="text/css">
	
	.card.small{
		display: none;
	}
</style>
<div class="card" style="padding: 5px;">
	
<div id="tag_cloud">
    
        <% tag_cloud Question.tag_counts, %w[sml med lar] do |tag, css_class| %>
           
   <div class="chip">
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    <i class="close material-icons">close</i>
  </div>
    
  <% end %>
    
</div>

</div>

app/views/home/users_list.html.erb
<style type="text/css">
  
  @import url(https://fonts.googleapis.com/css?family=Open+sans);
@import url(https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css);
@import url(https://fonts.googleapis.com/css?family=Playfair+Display);
.snip1515 {
  font-family: 'Open Sans', Arial, sans-serif;
  position: relative;
  float: left;
  margin: 10px 1%;
  min-width: 230px;
  max-width: 315px;
  width: 100%;
  color: #000000;
  text-align: center;
  line-height: 1.4em;
  font-size: 14px;
  box-shadow: none !important;
}

.snip1515:hover{
z-index: 8000;
    box-shadow: 0 12px 12px rgba(0, 0, .6, .6);

}

.snip1515 * {
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

.snip1515 .profile-image {
  display: inline-block;
  width: 80%;
  z-index: 1;
  position: relative;
  padding: 10px;
 /* border: 2px solid #e8b563;*/
}

.snip1515 .profile-image img {
  max-width: 100%;
  vertical-align: top;
}

.snip1515 figcaption {
  width: 100%;
  background-color: #F2F2F2;
  color: #555;
  padding: 125px 25px 25px;
  margin-top: -100px;
  display: inline-block;
}

.snip1515 h3,
.snip1515 h4,
.snip1515 p {
  margin: 0 0 5px;
}

.snip1515 h3 {
  font-weight: 600;
  font-size: 1.3em;
  font-family: 'Playfair Display', Arial, sans-serif;
}

.snip1515 h4 {
  color: #8c8c8c;
  font-weight: 400;
  letter-spacing: 2px;
   font-size: 1.0em;
}

.snip1515 p {
  font-size: 0.9em;
  letter-spacing: 1px;
  opacity: 0.9;
}

.snip1515 .icons {
  text-align: center;
  width: 100%;
}

.snip1515 i {
  padding: 10px 2px;
  display: inline-block;
  font-size: 18px;
  font-weight: normal;
  color: #e8b563;
  opacity: 0.75;
}

.snip1515 i:hover {
  opacity: 1;
  -webkit-transition: all 0.35s ease;
  transition: all 0.35s ease;
}


</style>
<div id="users">
<% @users.each do |u| %>
      <%= render 'user_list', user: u %>

<%end%>
 </div>

app/views/home/users_list.js.erb
<% @users.each do |u| %>
$('#users').append("<%= escape_javascript (render 'home/user_list', user: u) %>");
<% end %>