config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :notes
  get 'tags/:tag', to: 'home#index', as: :tag
  resources :questions
  resources :subtrends
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  resources :answers
  resources :questions
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  get 'home/index'
  get '/sear',to: 'questions#index'
  devise_for :users, :controllers => { sessions: "sessions", registrations: "registrations",:omniauth_callbacks => "omniauth_callbacks" }
  root to: "home#indexmain"
  resources :users,only: [:show,:edit,:update]
  get '/users_list'=>'home#users_list'
  get '/tags_list'=>'home#tags_list'

  resources :questions do
    post 'like',   to: 'socializations#like'
    post 'follow', to: 'socializations#followQuestion'
  end

  resources :answers do
    post 'like',   to: 'socializations#likeAnswer'
  end
  resources :trends do
    post 'follow', to: 'socializations#followTrend'
  end
  resources :users do
    post 'follow', to: 'socializations#followUser'
  
  end

end

app/views/layouts/_modal.html.erb
<style media="screen">
  #modal7 .modal-content{
    padding-top: 130px;
    padding: 2px;
  }
  .row2{
    padding-top: 10px;
  }
  .row1{
    padding-bottom: 3px;
    padding-left: 60px;
    padding-right: 60px;
  }
   .row1 input{
    color: #333;
   }
  .card-panel1{
    background: linear-gradient(60deg, #ab47bc, #7b1fa2);
    height: 120px;
    padding-top: 4px;
    padding-bottom: 4px;
    padding-left: 10px;
    padding-right: 10px;
    margin-left: 15px;
    margin-right: 15px;
    border-radius: 5px;
  }
  #tabsign a.active{
    /*background: #ff4b1f;  /* fallback for old browsers */
    /* background: -webkit-linear-gradient(to right, #ff9068, #ff4b1f);  /* Chrome 10-25, Safari 5.1-6 */
    /* background: linear-gradient(to right, #ff9068, #ff4b1f); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(60deg, #ab47bc, #7b1fa2);
    margin-left: -2px;
    margin-right: -2px;
    border-radius: 10px;
    color: white;
  }
  #tabsign a{
    color: #ab47bc;
  }
  .btt{
    background: linear-gradient(60deg, #ab47bc, #7b1fa2);
  }
</style>
<div class="row2">
  <ul id="tabsign" class="tabs tabs-fixed-width">
    <li class="tab col s6 "><a href="#test-swipe-1"> Sign In</a></li>
    <li class="tab col s6 "><a class="active" href="#test-swipe-2">Sign Up</a></li>
  </ul>
  <br>
  <div id="test-swipe-1">
    <div class="card-panel1 z-depth-4">
      <h5 class="white-text center-align">SIGN IN</h5>
      <div class="center-align">
        <%- if devise_mapping.omniauthable? %>
        <%- resource_class.omniauth_providers.each do |provider| %>
        <a class="waves-effect waves-light btn transparent"><i class="fa fa-twitter"></i></a>
        <%= link_to ('<i class="fa fa-facebook-square"></i>').html_safe, omniauth_authorize_path(resource_name, :facebook),class:"waves-effect waves-light btn transparent"%><br />
        <% end -%>
        <% end -%>
        <!-- <a class="waves-effect waves-light btn transparent"><i class="fa fa-google-plus"></a> -->
      </div>
    </div>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
    <form class="col s12">
      <div class="row1">
        <div class="input-field col s12">
          <i class="material-icons prefix">account_circle</i>
          <input type="text" class="validate">
          <label for="name">Username</label>
        </div>
        <div class="input-field col s12">
          <i class="material-icons prefix">email</i>
          <!-- <input id="email" type="email" class="validate"> -->
          <%= f.email_field :email, autofocus: true, class:"validate"%>
          <label for="user_email", class="">Email</label>
        </div>
        <div class="input-field col s12">
          <i class="material-icons prefix">lock_outline</i>
          <!-- <input id="password" type="password" class="validate"> -->
          <%= f.password_field :password, autocomplete: "off", class:"validate" %>
          <label for="user_password">Password</label>
        </div>
        <br>
        <div class="">
          <!-- <input type="checkbox" id="checksubmit" /> -->
          <!-- <label for="checksubmit">Remember me</label> -->
          <% if devise_mapping.rememberable? -%>
          <%= f.check_box :remember_me %>
          <label for="user_remember_me">Remember me</label>
          <!-- <%= f.label :remember_me %> -->
          <% end %> </p>
          <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
          <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
          <% end -%>
          <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
          <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
          <% end -%>
        </div>
        <br>
        <button class="btn waves-effect waves-light purple darken-3 right btt white-text" type="submit" name="action">
          <i class="material-icons right">send</i>SUBMIT</button>
          <br>
        </div>
      </form>
      <%end%>
    </div>
    <div id="test-swipe-2">
      <div class="card-panel1 purple darken-3 z-depth-4">
        <h5 class="white-text center-align">SIGN UP</h5>
        <div class="center-align">
          <%- if devise_mapping.omniauthable? %>
          <%- resource_class.omniauth_providers.each do |provider| %>
          <a class="waves-effect waves-light btn transparent"><i class="fa fa-twitter"></i></a>
          <%= link_to ('<i class="fa fa-facebook-square"></i>').html_safe, omniauth_authorize_path(resource_name, :facebook),class:"waves-effect waves-light btn transparent"%><br />
          <% end -%>
          <% end -%>
          <!-- <a class="waves-effect waves-light btn transparent"><i class="fa fa-google-plus"></a> -->
        </div>
      </div>
      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= devise_error_messages! %>
      <form class="col s12">
        <div class="row1">
          <div class="input-field col s12">
            <i class="material-icons prefix">account_circle</i>
            <!-- <input id="name" type="text" class="validate"> -->
            <%=f.text_field :name, autofocus: true,class:"validate"%>
            <label for="user_name">Username</label>
          </div>
          <div class="input-field col s12">
            <i class="material-icons prefix">email</i>
            <!-- <input id="email" type="email" class="validate"> -->
            <%= f.email_field :email, autofocus: true,class:"validate"%>
            <label for="user_email">Email</label>
          </div>
          <div class="input-field col s12">
            <i class="material-icons prefix">lock_outline</i>
            <!-- <input id="password" type="password" class="validate"> -->
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %>
            <%= f.password_field :password, autocomplete: "off", class:"validate"%>
            <label for="user_password">Password</label>
          </div>
          <div class="input-field col s12">
            <i class="material-icons prefix">lock_outline</i>
            <!-- <input id="password" type="password" class="validate"> -->
            <%= f.password_field :password_confirmation, autocomplete: "off", class:"validate" %>
            <label for="user_password">Confirm Password</label>
          </div>
          <br>
          <button class="btn waves-effect waves-light purple darken-3 right btt white-text" type="submit" name="action">
            <i class="material-icons right">send</i>SUBMIT</button>
            <br>
          </div>
        </form>
        <%end%>
      </div>
    </div>

app/views/layouts/_modaladdnote.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_modalshownote.html.erb
 <%if Note.where(:user_id => current_user.id).length>0%>

        <p class="truncate">  <%= Note.where(:user_id => current_user.id).last.content %></p><%end%>
        <br>
        <hr><%if Note.where(:user_id => current_user.id).length>=2%>
        <br>
        <p class="truncate"><%= Note.where(:user_id => current_user.id)[-2].content %><%end%>
        </p>

app/views/layouts/_modaltag.html.erb
<div id="tag_cloud">
    
        <% tag_cloud Question.tag_counts, %w[sml med lar] do |tag, css_class| %>
           
   <div class="chip">
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <i class="material-icons tagicon">add</i>
  </div>
    
  <% end %>
    
</div>

app/views/layouts/_sideques.html.erb
 
<style type="text/css">
	
	.card.quesrelate{
		width:270px;
	}
		.card.quesrelate hr{
			    color: #dddfe7;

		}
</style>



<% if @questagfeed != nil %>


 <div class="card quesrelate"> 
<div class="card-title center" style="color:#696a6e;font-size: 28px;font-weight: 800;font-family: Fresca,sans-serif;"> 
Related Questions
</div>
<div class="card-content">
	

 <% @questagfeed.each do |ques| %>
   <%= link_to ques.title, ques %>
   <hr>
   <% end %>
</div>
 </div>
     <% end %>